# Content for the Garo Private Portfolio. Prices, unit counts and statuses are as quoted in the
# Mizan Qist residential portfolio (MQ Portfolio 2.html, August 2026); Lake Chad and Cova Manor
# facts come from the Maitama View and Cova Manor brochures.

CLIENT = "H.E. Murtala Sule Garo"
CLIENT_SHORT = "Mr Murtala Sule Garo"
AGENT = "Mr Sadiq Babalele"
DATE = "September 2026"

SITES = [
 dict(id="d01", n="01", name="Lake Chad", scheme="Maitama View", street="Lake Chad Crescent", plot="Plot 758, Cadastral Zone A05",
      district="Maitama", city="Abuja", status="Off-plan", dev="Wrace", arch="Abdullahi Ndanusa & Arc. Daniel S. Akpama · working drawings, July 2026",
      price="₦1.5bn – ₦1.85bn", pmin=1500, pmax=1850, units="9", avail="9", beds="4 – 5",
      types=[("Detached duplex", "5 bedrooms, all en suite · 1 BQ", "≈ 345 – 377 m²", "5", "₦1.85bn"),
             ("Semi-detached", "4 bedrooms, all en suite · 1 BQ", "≈ 252 m²", "4", "₦1.5bn")],
      facts=[("Site", "3,274", "m²"), ("Built at ground", "28.2", "%"), ("Storeys", "3", ""), ("Palms, trees & shrubs", "1,149", "")],
      view="Nine homes behind one gate in the diplomatic quarter, with the working drawings complete, so the specification is settled before a block is laid. Two ways to hold it: the five detached duplexes along the eastern boundary as a single purchase, or the whole enclave. Off-plan pricing applies at this stage.",
      hero=("lc-hero", "wide", "Visualisation · the row of detached duplexes along the private avenue"),
      gallery=[("Concept", "lc-dusk", "The semi-detached pair at dusk"), ("Concept", "lc-row", "The row of five detached duplexes"), ("Concept", "lc-corner", "The cantilever, from the corner"),
               ("Concept", "lc-avenue", "Along the avenue"), ("Concept", "lc-avenue-corner", "From the avenue, towards the pair"), ("Concept", "lc-front", "The pair by day"), ("Site plan", "lc-aerial", "The enclave from above · nine plots")],
      short="Nine homes, one gate, Maitama."),

 dict(id="d02", n="02", name="Gana Street", scheme="", street="Gana Street", plot="",
      district="Maitama", city="Abuja", status="Selling", dev="Cova", arch="",
      price="₦350m – ₦700m", pmin=350, pmax=700, units="30", avail="—", beds="3",
      types=[("Apartment", "3 bedrooms", "", "", "₦350m"), ("Terrace", "3 bedrooms", "", "", "₦700m")],
      facts=[("Homes", "30", ""), ("House types", "2", ""), ("Bedrooms", "3", "in every home"), ("Status", "Selling", "")],
      view="Thirty three-bedroom homes on Gana Street, in the heart of Maitama, split between apartments and terraces. At ₦350m an apartment is the lowest entry price in Maitama on this file, and the terraces at ₦700m sit well under the district's detached houses. Construction is under way. A letting or resale hold rather than a residence.",
      hero=("gana-c1", "split", "Concept render · the courtyard between the blocks"),
      gallery=[("Concept", "gana-c1", "The courtyard"), ("Concept", "gana-c2", "The blocks from the drive"), ("Current state", "gana-s1", "The frame, from the street"), ("Current state", "gana-s2", "The frame · east elevation"), ("Current state", "gana-s3", "Along the frame")],
      short="Thirty homes, the Maitama entry price."),

 dict(id="d03", n="03", name="Agulu Lake", scheme="", street="Agulu Lake Street", plot="",
      district="Maitama", city="Abuja", status="Selling", dev="", arch="",
      price="₦6.6bn", pmin=6600, pmax=6600, units="28", avail="4", beds="5",
      types=[("Detached villa", "5 bedrooms", "580 m²", "4", "₦6.6bn")],
      facts=[("Villa", "580", "m²"), ("Bedrooms", "5", ""), ("Available", "4", "of 28 in the scheme"), ("Site photography", "22 Aug", "2026")],
      view="Four detached villas of 580 m² on Agulu Lake Street, each with five bedrooms, and the frame already up. The render shows the intent: a stone-and-render façade outlined in light at dusk, glass balustrades, a paved forecourt. At ₦6.6bn a villa this is the largest single ticket in the file, and the first we would show for a principal residence.",
      hero=("agulu-render", "wide", "Visualisation · the villa at dusk, light beneath every edge"),
      gallery=[("Concept", "agulu-render", "The villa at dusk"), ("Current state", "agulu-s1", "The frame from the road"), ("Current state", "agulu-s2", "The frame · front"), ("Current state", "agulu-s3", "From above"), ("Current state", "agulu-s4", "The street, looking east")],
      short="Five bedrooms, 580 m², the largest ticket."),

 dict(id="d04", n="04", name="Heights 777", scheme="", street="Parakou Street", plot="Plot 777, Cadastral Zone A07",
      district="Wuse II", city="Abuja", status="Off-plan", dev="Wrace Group", arch="Arc. Anthony C. N. · drawings, October 2025",
      price="₦350m – ₦400m", pmin=350, pmax=400, units="32", avail="18", beds="1 – 2",
      types=[("1-bed apartment", "1 bedroom", "", "6", "₦350m"), ("2-bed apartment", "2 bedrooms", "", "12", "₦400m")],
      facts=[("Storeys", "7", ""), ("Site", "1,136", "m²"), ("Parking bays", "21", ""), ("Rooftop", "Pool", "infinity pool on the top floor")],
      view="A seven-storey building of one- and two-bedroom apartments on Parakou Street, Wuse II, by Wrace, with a rooftop infinity pool and twenty-one parking bays. Eighteen apartments remain of thirty-two. Small tickets, suited to taking whole floors for letting rather than single units.",
      hero=("h777-corner-dusk", "tall", "Visualisation · the corner at dusk"),
      gallery=[("Concept", "h777-corner-dusk", "The corner at dusk"), ("Concept", "h777-entrance-dusk", "The entrance at dusk"), ("Concept", "h777-front-clear", "The front, clear sky"), ("Concept", "h777-street-day", "From the street"), ("Concept", "h777-balconies", "The balconies from above"), ("Concept", "h777-entrance-day", "The entrance by day"), ("Concept", "h777-front-overcast", "The front, overcast")],
      short="Seven storeys of apartments, Wuse II."),

 dict(id="d05", n="05", name="Katampe", scheme="Opposite Deda", street="Katampe Extension", plot="",
      district="Katampe Ext.", city="Abuja", status="Off-plan", dev="Wrace & Cova", arch="",
      price="₦600m – ₦800m", pmin=600, pmax=800, units="36", avail="8", beds="2 – 6",
      types=[("Detached villa", "6 bedrooms · 1 BQ", "", "3", "₦800m carcass"), ("Semi-detached", "6 bedrooms · 1 BQ", "", "5", "₦600m carcass"),
             ("Terrace", "3 bedrooms", "230 m²", "12", "Sold out"), ("Apartment", "2 bedrooms", "150 m²", "8", "Not listed")],
      facts=[("Homes", "36", ""), ("House types", "4", ""), ("Detached & semi", "8", "available, sold as carcass"), ("Site photography", "22 Aug", "2026")],
      view="Thirty-six homes in four types on Katampe Extension, opposite Deda, by Wrace and Cova, with the foundations in the ground. The six-bedroom detached and semi-detached houses are sold as carcass, so the finishing is yours to specify; the terraces are sold out and the apartments not yet released. The value is in the carcass pricing and in buying before the frames go up.",
      hero=("kat-c1", "split", "Concept render · the terraces and the detached row"),
      gallery=[("Concept", "kat-c1", "The estate"), ("Concept", "kat-c2", "A detached villa"), ("Concept", "kat-c3", "The detached row"), ("Concept", "kat-c4", "A semi-detached pair"), ("Concept", "kat-c5", "The terraces"), ("Concept", "kat-c6", "Along the terraces"), ("Concept", "kat-c7", "The terraces, corner"),
               ("Site plan", "kat-plan1", "Masterplan render"), ("Site plan", "kat-plan2", "Site layout drawing"),
               ("Current state", "kat-s1", "Foundations from above"), ("Current state", "kat-s2", "The footprint"), ("Current state", "kat-s3", "Ground works"), ("Current state", "kat-s4", "The terraces' foundations"), ("Current state", "kat-s5", "Across the site"), ("Current state", "kat-s6", "Close over the works")],
      short="Thirty-six homes, carcass pricing."),

 dict(id="d06", n="06", name="Utako", scheme="", street="Utako", plot="",
      district="Mabushi District", city="Abuja", status="Ready", dev="Wrace", arch="",
      price="₦500m – ₦900m", pmin=500, pmax=900, units="30", avail="7", beds="3 – 5",
      types=[("Detached villa", "5 bedrooms · 1 BQ", "", "4", "₦900m · ₦820m carcass"), ("Semi-detached", "5 bedrooms · 1 BQ", "", "3", "₦650m · ₦500m carcass"),
             ("Terrace", "3 bedrooms", "235 m²", "10", "Not listed"), ("Apartment", "3 bedrooms · 1 BQ", "", "", "Not listed")],
      facts=[("Homes", "30", ""), ("House types", "4", ""), ("Detached & semi", "7", "available, finished or carcass"), ("Site photography", "22 Aug", "2026")],
      view="Thirty homes in Mabushi District, ready, with detached and semi-detached five-bedroom houses offered finished or as carcass. The detached villa at ₦900m, or ₦820m as carcass, is the one to walk through; the terraces and apartments are not listed for sale.",
      hero=("utako-s8", "wide", "Site photograph · the row of villas, 22 August 2026"),
      gallery=[("Site plan", "utako-plan", "Site layout"), ("Concept", "utako-c1", "The avenue"), ("Concept", "utako-c2", "The villas"), ("Current state", "utako-s1", "The estate from above"), ("Current state", "utako-s2", "The villa row"), ("Current state", "utako-s8", "The villas, close"), ("Current state", "utako-s3", "The apartment block"), ("Current state", "utako-s9", "The block, from the road"), ("Current state", "utako-s4", "The block · east"), ("Current state", "utako-s5", "The terraces"), ("Current state", "utako-s6", "Foundations, west"), ("Current state", "utako-s7", "The frame")],
      short="Ready five-bedroom villas, Mabushi."),

 dict(id="d07", n="07", name="Olakunle Gidado", scheme="", street="Olakunle Gidado Street", plot="",
      district="Guzape", city="Abuja", status="Ready", dev="", arch="",
      price="₦1.5bn – ₦1.8bn", pmin=1500, pmax=1800, units="26", avail="1", beds="5",
      types=[("Detached villa", "5 bedrooms · 2 BQ", "", "1", "₦1.5bn – ₦1.8bn")],
      facts=[("Bedrooms", "5", ""), ("Boys' quarters", "2", ""), ("Available", "1", "the last of 26"), ("Status", "Ready", "")],
      view="A completed five-bedroom villa with two BQs on Olakunle Gidado Street, Guzape, the last of twenty-six in its scheme. Ready to view; the photographed interior is unfinished, so the fit-out can still be to your taste.",
      hero=("og-s1", "split", "Site photograph · the villa from the street"),
      gallery=[("Current state", "og-s1", "From the street"), ("Current state", "og-s2", "The entrance"), ("Current state", "og-s3", "The pair"), ("Current state", "og-s4", "Interior · unfinished")],
      short="The last villa of twenty-six, Guzape."),

 dict(id="d08", n="08", name="Mississippi", scheme="", street="Mississippi Street", plot="",
      district="Maitama", city="Abuja", status="Selling", dev="", arch="",
      price="₦4.1bn", pmin=4100, pmax=4100, units="1", avail="1", beds="5 + 2",
      types=[("Existing house", "5 bedrooms · 2-bedroom guest chalet", "", "1", "₦4.1bn")],
      facts=[("Bedrooms", "5", "plus a two-bedroom guest chalet"), ("Occupied", "Yes", "the landowner is in residence"), ("Photography", "None", "deferred, out of courtesy"), ("Best use", "Rebuild", "")],
      view="A long-established house on Mississippi Street, one of Maitama's oldest addresses, still occupied by the landowner, who is now selling. Five bedrooms and a two-bedroom guest chalet, at ₦4.1bn. We have not photographed the house out of courtesy to the occupant. The value here is the land and the street, not the building: we recommend acquiring the plot for demolition and new construction rather than renovation, and commissioning a design for the site.",
      hero=("", "diagram", "Illustrative diagram · not a survey · not to scale"),
      gallery=[],
      short="An old house on the land you want."),

 dict(id="d09", n="09", name="Linda Chalker", scheme="", street="Linda Chalker Street", plot="",
      district="Asokoro", city="Abuja", status="Off-plan", dev="", arch="",
      price="₦900m", pmin=900, pmax=900, units="1", avail="1", beds="5",
      types=[("Detached villa", "5 bedrooms · 3 living rooms · 1 BQ", "", "1", "₦900m")],
      facts=[("Bedrooms", "5", ""), ("Living rooms", "3", ""), ("Boys' quarters", "1", ""), ("Status", "Off-plan", "frame up")],
      view="A five-bedroom detached villa with three living rooms and a BQ on Linda Chalker Street, Asokoro, off-plan at ₦900m. The structure is up, and the concept renders show a white cantilevered form with a screened balcony and light beneath every edge. One home only.",
      hero=("linda-c1", "tall", "Visualisation · the corner at dusk"),
      gallery=[("Concept", "linda-c1", "The corner at dusk"), ("Concept", "linda-c2", "The approach"), ("Concept", "linda-c3", "The entrance"), ("Concept", "linda-c4", "From above"), ("Current state", "linda-s1", "The site from above"), ("Current state", "linda-s2", "The frame"), ("Current state", "linda-s3", "The frame · side"), ("Current state", "linda-s4", "The structure"), ("Current state", "linda-s5", "Ground floor")],
      short="One villa, three living rooms, Asokoro."),

 dict(id="d10", n="10", name="Cova Manor", scheme="", street="1053 Abagbon Close, off Ologun Agbaje Street", plot="",
      district="Victoria Island", city="Lagos", status="Off-plan", dev="Cova International Company", arch="Q-Form Designs · construction documentation, July 2026",
      price="On application", pmin=0, pmax=0, units="8", avail="8", beds="2 – 4",
      types=[("Duplex", "4 bedrooms · guest suite · staff room", "≈ 283 – 317 m²", "6", "On application"), ("Apartment", "2 bedrooms", "≈ 130 – 145 m²", "2", "On application")],
      facts=[("Site", "835", "m²"), ("Levels", "8", "seven floors over an open court"), ("Parking bays", "17", ""), ("Lift", "Otis", "machine-room-less passenger lift")],
      view="The one address outside Abuja. Eight residences on a quiet close in Victoria Island: six four-bedroom duplexes and two apartments in white decks over an open parking court, with a lift and seventeen bays, one turn from Adeola Odeku. Construction documentation is complete. Price on application; we include it for a Lagos base of matching quality.",
      hero=("cova-corner", "split", "Visualisation · the corner from the close"),
      gallery=[("Concept", "cova-corner", "From the close"), ("Concept", "cova-front", "The long elevation"), ("Concept", "cova-approach", "The approach"), ("Plan", "cova-plan-duplex-lower", "Duplex · living floor"), ("Plan", "cova-plan-duplex-upper", "Duplex · bedroom floor"), ("Plan", "cova-plan-first", "First floor · apartments")],
      short="Eight residences, Victoria Island."),
]
